name: 03 - Ansible Provision

on:
  workflow_call:
    inputs:
      bastion_ip:
        required: true
        type: string
      lb_dns:
        required: true
        type: string

  workflow_dispatch:
    inputs:
      bastion_ip:
        description: "Bastion Public IP"
        required: true
      lb_dns:
        description: "K8s API Load Balancer DNS"
        required: true

env:
  AWS_REGION: us-east-1
  ANSIBLE_HOST_KEY_CHECKING: "False"

jobs:
  provision:
    name: Setup Kubernetes Cluster
    runs-on: ubuntu-latest

    steps:
      - name: ðŸ“¥ Checkout Code
        uses: actions/checkout@v4

      - name: ðŸ Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: ðŸ“¦ Install Ansible
        run: |
          pip install ansible-core

      - name: ðŸ” Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: ðŸ”‘ Prepare SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/petclinic-test-key.pem
          chmod 400 ~/.ssh/petclinic-test-key.pem

      - name: ðŸ“ Generate Inventory
        working-directory: ansible-k8s-setup
        run: |
          BASTION="${{ inputs.bastion_ip }}"
          LB="${{ inputs.lb_dns }}"

          echo "[bastion]" > inventory/hosts.ini
          echo "bastion ansible_host=$BASTION ansible_user=ubuntu" >> inventory/hosts.ini

          echo "" >> inventory/hosts.ini
          echo "[masters]" >> inventory/hosts.ini

          jq -r '.[]' ../terraform-k8s-infrastructure/master_ips.json | nl -v1 | while read n ip; do
            echo "master-$n ansible_host=$ip node_index=$n" >> inventory/hosts.ini
          done

          echo "" >> inventory/hosts.ini
          echo "[workers]" >> inventory/hosts.ini

          jq -r '.[]' ../terraform-k8s-infrastructure/worker_ips.json | nl -v1 | while read n ip; do
            echo "worker-$n ansible_host=$ip node_index=$n" >> inventory/hosts.ini
          done

          sed -i "s|control_plane_endpoint:.*|control_plane_endpoint: \"$LB:6443\"|" inventory/group_vars/all.yml

      - name: ðŸ”Œ Test SSH
        working-directory: ansible-k8s-setup
        run: ansible all -i inventory/hosts.ini -m ping

      - name: ðŸš€ Run Full Ansible Deployment
        working-directory: ansible-k8s-setup
        run: ansible-playbook playbooks/complete-setup.yml -i inventory/hosts.ini
